metrics:
  # list of couples with metric: metric name and coef: double
  # - at least one quality metric
  # - at least one cost metric
  # - sum of coefs for quality metrics must be 1
  - metric: CVE
    coef: 0.6
  - metric: FRESHNESS
    coef: 0.2
  - metric: POPULARITY_1_YEAR
    coef: 0.2
  - metric: COST
    coef: 0.5
constraints:
  # list (possibly empty) of contraints with constraint: and value:
  # a constraint can be one of:
  # - constraint: COST_LIMIT and value: double
  # - constraint: PRESENCE and value: some id
  # - constraint: ABSENCE and value: some id
releases:
  focus: ROOT # either NONE, ROOT, CONSTRAINTS (root + all libs of releases in ABSENCE), or ALL
  selectors: [MORE_RECENT] # combination of MORE_RECENT, NO_PATCHES (can be empty to select all)
costs:
  focus: ROOT # either NONE, ROOT, CONSTRAINTS (root + all libs of releases in ABSENCE), or ALL
  default: 9999999.9 # default value for unknown costs
  tool-direct: MARACAS # either NONE or MARACAS
  tool-indirect: NONE # either NONE or JAPICMP