metrics:
  - metric: CVE
    coef: 0.6
  - metric: FRESHNESS
    coef: 0.2
  - metric: POPULARITY_1_YEAR
    coef: 0.2
  - metric: COST
    coef: 0.5
constraints:
  # - constraint: COSTLIMIT
  #   value: 0.0
  # - constraint: PRESENCE
  #   value: "some identification"
  # - constraint: ABSENCE
  #   value: "some other identification"