#
# update configuration file
#
metrics:
  # list of couples with metric: metric name and coef: double
  # - at least one quality metric
  # - at least one cost metric
  # - sum of coefs for quality metrics must be 1
  - metric: CVE
    coef: 0.6
  - metric: FRESHNESS
    coef: 0.2
  - metric: POPULARITY_1_YEAR
    coef: 0.2
  - metric: COST
    coef: 0.5
constraints:
  # list (possibly empty) of constraints with constraint: and value:
  # a constraint can be one of:
  # - constraint: COST_LIMIT and value: double -> maximum value of total cost of solution
  # - constraint: CVE_LIMIT and value: double -> maximum value of total CVE of solution
  # - constraint: PRESENCE and value: some id -> id must be present in solution
  # - constraint: ABSENCE and value: some id -> id must be absent in solution
  # notes:
  # - if you use both PRESENCE and ABSENCE for some same id, there is no solution
  # - if you use COST_LIMIT and no solution exist under this limit, there is no solution
  - constraint: COST_LIMIT
    value: 0.0
  - constraint: CVE_LIMIT
    value: 0.0
  - constraint: PRESENCE
    value: "group:artifact:version"
  - constraint: ABSENCE
    value: "groupe:artifact:version"
releases:
  # either NONE, ROOT, CONSTRAINTS (root + all libs of releases in ABSENCE), or ALL
  # (!!) by now only ROOT is supported
  focus: ROOT
  # combination of MORE_RECENT, NO_PATCHES (can be empty to select all)
  # (!!) by now only MORE_RECENT is supported
  selectors: [MORE_RECENT]
costs:
   # either NONE, ROOT, CONSTRAINTS (root + all libs of releases in ABSENCE), or ALL
   # (!!) by now only NONE, ROOT, and ALL are supported
  focus: ROOT
  # default value for unknown costs, MAX or MIN
  default: MAX
  # tool used to compute costs at root level, either NONE or MARACAS
  # (!!) by now only MARACAS is supported
  tool-direct: MARACAS
  # tool used to compute costs at non-root level, either NONE or JAPICMP
  # (!!) by now only NONE is supported
  tool-indirect: NONE